=head1 NAME

nbdsh - network block device (NBD) shell

=head1 SYNOPSIS

 $ nbdsh
 
 Welcome to nbdsh, the shell for interacting with
 Network Block Device (NBD) servers.
 
 The ‘nbd’ module has already been imported and there
 is an open NBD handle called ‘h’.
 
 nbd> h.connect_command (["nbdkit", "-s", "memory", "1G"])
 nbd> h.get_size ()
 1073741824
 nbd> buf = b"hello, world"
 nbd> h.pwrite (buf, 0, 0)
 nbd> exit()

 $ nbdsh --connect nbd://localhost -c 'print (h.get_size ())'
 1073741824

=head1 DESCRIPTION

nbdsh is a Python-based client shell for accessing Network Block
Device (NBD) servers.

For documentation about the libnbd API please open the shell and type:

 help (nbd)

=head1 OPTIONS

=over 4

=item B<-h>

=item B<--help>

Display brief command line help and exit.

=item B<-c> 'COMMAND ...'

=item B<--command> 'COMMAND ...'

Instead of starting an interactive shell, run a command.  This option
can be specified multiple times in order to run multiple commands.

=item B<--connect> URI

Connect to the given NBD URI.  This is equivalent to the
S<C<h.connect_uri (URI)>> command in the shell.

=item B<-V>

=item B<--version>

Display the package name and version and exit.

=back

=head1 SEE ALSO

L<libnbd(3)>,
L<libnbd-api(3)>,
L<qemu-img(1)>.

=head1 AUTHORS

Richard W.M. Jones

=head1 COPYRIGHT

Copyright (C) 2019 Red Hat Inc.
