=head1 NAME

nbdinfo - display information and metadata about NBD servers and exports

=head1 SYNOPSIS

 nbdinfo [--json] [--size] NBD-URI

 nbdinfo -L|--list NBD-URI

 nbdinfo --help

 nbdinfo --version

=head1 EXAMPLES

 nbdinfo nbd://localhost

 nbdinfo "nbd+unix:///?socket=/tmp/unixsock"

 nbdinfo --size nbd://example.com

 nbdinfo --json nbd://example.com

 nbdinfo --list nbd://example.com

=head1 DESCRIPTION

nbdinfo displays information and metadata about an NBD server.  The
only required parameter is the NBD URI of the server (see
L<https://github.com/NetworkBlockDevice/nbd/blob/master/doc/uri.md>):

 $ nbdinfo nbd://localhost
 protocol: newstyle-fixed without TLS
 export="":
         export-size: 1048576
         content: data
         is_rotational: false
         is_read_only: false
         can_cache: true
         can_df: true
         can_fast_zero: true
         can_flush: true
         can_fua: true
         can_multi_conn: true
         can_trim: true
         can_zero: true

To display only the size in bytes of the NBD export (useful for
scripting) use the I<--size> parameter:

 $ nbdinfo --size nbd://localhost
 1048576

To display the output as JSON (eg. for scripting with L<jq(1)>) add
the I<--json> parameter:

 $ nbdinfo --json nbd://localhost | jq
 {
   "protocol": "newstyle-fixed",
   "TLS": false,
   "exports": [
     {
       "export-name": "",
       "content": "DOS/MBR boot sector; partition 1 : ID=0xc, start-CHS (0x3ff,254,63), end-CHS (0x3ff,254,63), startsector 2048, 4148704 sectors",
       "is_rotational": false,
       "is_read_only": true,
       "can_cache": true,
       "can_df": true,
       "can_fast_zero": false,
       "can_flush": false,
       "can_fua": false,
       "can_multi_conn": true,
       "can_trim": false,
       "can_zero": false,
       "export-size": 2125119488
     }
   ]
 }

To list all the exports available on an NBD server use the I<--list>
(I<-L>) option.

=head2 Alternative tools

You could use S<C<qemu-img info>> (see L<qemu-img(1)>) to query a
single export from an NBD server.  S<C<qemu-nbd -L>> (see
L<qemu-nbd(8)>) can list NBD exports.  L<nbdsh(1)> or the L<libnbd(3)>
API can be used for more complex queries.

=head1 OPTIONS

=over 4

=item B<--help>

Display brief command line help and exit.

=item B<--content>

=item B<--no-content>

Mostly the information displayed comes from the metadata sent by the
NBD server during the handshake.  However nbdinfo also downloads a
small amount of data from the beginning of the export to try to probe
the content with L<file(1)>.

When I<not> using I<--list>, the default is I<--content>, ie.  probing
the content.  To prevent content probing, use I<--no-content>.

When using I<--list>, the default is I<--no-content> (since
downloading from each export is expensive).  To enable content probing
use I<--list --content>.

=item B<--json>

The output is displayed in JSON format.

=item B<-L>

=item B<--list>

List all the exports on an NBD server.  The export name in the NBD URI
is ignored.

=item B<--size>

Display only the size in bytes of the export.

=item B<-V>

=item B<--version>

Display the package name and version and exit.

=back

=head1 SEE ALSO

L<libnbd(3)>,
L<nbdcopy(1)>,
L<nbdfuse(1)>,
L<nbdsh(1)>,
L<file(1)>,
L<jq(1)>,
L<qemu-img(1)>,
L<qemu-nbd(8)>.

=head1 AUTHORS

Richard W.M. Jones

=head1 COPYRIGHT

Copyright (C) 2020 Red Hat Inc.
