=head1 NAME

libnbd-ocaml - how to use libnbd from OCaml

=head1 SYNOPSIS

 let nbd = NBD.create () in
 NBD.connect_uri nbd "nbd://localhost";
 let size = NBD.get_size nbd in
 printf "%Ld\n" size

=head1 DESCRIPTION

This manual page documents how to use libnbd to access Network Block
Device (NBD) servers from the OCaml programming language.  The OCaml
bindings work very similarly to the C bindings so you should start by
reading L<libnbd(3)>.

=head1 HANDLES

Create a libnbd handle of type C<NBD.t> by calling S<C<NBD.create ()>>.

You can either close the handle explicitly by calling C<NBD.close> or
it will be closed automatically when it is garbage collected.  If you
call any other method on a handle which you have explicitly closed
then the API will throw an C<NBD.Closed> exception.

=head1 ERRORS

Libnbd errors are turned automatically into S<C<NBD.Error (str, errno)>>
exceptions.  This exception has two parameters.  The first is a string
which is the printable error message.  The second is the raw C<errno>,
if available (see L<nbd_get_errno(3)>).  The raw C<errno> is not
compatible with errors in the OCaml C<Unix> module unfortunately.

=head1 EXAMPLES

This directory contains examples written in OCaml:

L<https://github.com/libguestfs/libnbd/tree/master/ocaml/examples>

=head1 SEE ALSO

L<libnbd(3)>.

=head1 AUTHORS

Richard W.M. Jones

=head1 COPYRIGHT

Copyright (C) 2019 Red Hat Inc.
