#!/bin/sh

if test -z "$1"
then
    echo "syntax: $0 PATH-TO-LCITOOL"
    exit 1
fi

LCITOOL=$1

if ! test -x "$LCITOOL"
then
    echo "$LCITOOL is not executable"
    exit 1
fi

ci_path=$(dirname "$0")

for target in $($LCITOOL targets)
do
    if echo "$target" | grep -q -e 'freebsd' -e 'macos'
    then
        $LCITOOL variables "$target" libnbd >"$ci_path/cirrus/$target.vars"
    else
        $LCITOOL dockerfile "$target" libnbd >"$ci_path/containers/$target.Dockerfile"
    fi
done
